name: Build OpenWrt (Ubuntu 24.04)

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -e
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libncurses5-dev libssl-dev libelf-dev \
            python3 python3-pip python3-setuptools python3-distutils python3-distutils-extra \
            rsync unzip zlib1g-dev file wget curl cpio time patch quilt \
            libtool autopoint autoconf automake pkg-config libglib2.0-dev \
            libxml-parser-perl intltool gettext-base \
            libgmp-dev libmpc-dev libmpfr-dev libreadline-dev \
