name: Build OpenWrt (Ubuntu 24.04)

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev libelf-dev \
            python3 python3-pip python3-setuptools \
            rsync unzip zlib1g-dev file wget curl cpio time patch quilt \
            libtool autopoint autoconf automake pkg-config libglib2.0-dev \
            libxml-parser-perl intltool gettext-base \
            libgmp-dev libmpc-dev libmpfr-dev libreadline-dev \
            liblz4-dev libzstd-dev liblzma-dev libbz2-dev libzip-dev \
            libpcap-dev libnl-3-dev libnl-genl-3-dev libpam0g-dev libgnutls28-dev \
            libsodium-dev libgcrypt20-dev nettle-dev \
            zip p7zip-full unrar xz-utils zstd lzip ncompress tar swig gperf \
            device-tree-compiler xmlstarlet xsltproc docbook-xsl docbook-xml \
            perl ecj fastjar openjdk-11-jdk-headless java-common \
            asciidoc help2man subversion mercurial graphviz ccache

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/pesa1234/openwrt.git
          cd openwrt
          export FORCE_UNSAFE_CONFIGURE=1
          git checkout next-r4.6.14.rss.mtk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add custom UCI configuration
        run: |
          cd openwrt
          mkdir -p files/etc/uci-defaults
          cat << 'EOF' > files/etc/uci-defaults/99-custom-settings
          #!/bin/sh

          uci set network.tailscale=interface
          uci set network.tailscale.proto='none'
          uci set network.tailscale.device='tailscale0'
          uci del dhcp.lan.ra_slaac
          uci set dhcp.lan.force='1'
          uci set network.lan.netmask='255.255.255.0'
          uci set dhcp.lan.netmask='255.255.255.0'
          uci set network.lan.ipaddr='192.168.2.1'
          uci add_list dhcp.lan.dhcp_option='6,192.168.2.1'
          uci set network.wan.proto='pppoe'
          uci set network.wan.username='valdirenepereiradefreitas'
          uci set network.wan.password='102030'
          uci set network.wan.ipv6='auto'

          uci set network.wan.peerdns='0'
          uci add_list network.wan.dns='8.8.8.8'
          uci set network.wan6.peerdns='0'
          uci add_list network.wan6.dns='2001:4860:4860::8888'
          uci commit network

          uci del system.ntp.enabled
          uci del system.ntp.enable_server
          uci set system.cfg01e48a.zonename='America/Sao Paulo'
          uci set system.cfg01e48a.timezone='<-03>3'
          uci del system.ntp.server
          uci add_list system.ntp.server='162.159.200.1'
          uci add_list system.ntp.server='162.159.200.123'
          uci commit system

          uci set wireless.radio0.disabled='0'
          uci set wireless.radio0.channel='auto'
          uci set wireless.radio0.htmode='HE20'
          uci set wireless.radio0.country='US'
          uci set wireless.radio0.cell_density='0'
          uci set wireless.default_radio0.ssid='3Valdirene'
          uci set wireless.default_radio0.encryption='psk2+ccmp'
          uci set wireless.default_radio0.key='Cafequente.423'
          uci set wireless.default_radio0.disassoc_low_ack='0'

          uci set wireless.radio1.disabled='0'
          uci set wireless.radio1.channel='auto'
          uci set wireless.radio1.htmode='HE160'
          uci set wireless.radio1.country='US'
          uci set wireless.radio1.cell_density='0'
          uci set wireless.default_radio1.ssid='0R4'
          uci set wireless.default_radio1.encryption='psk2+ccmp'
          uci set wireless.default_radio1.key='Cafequente.423'
          uci set wireless.default_radio1.disassoc_low_ack='0'
          uci commit wireless

          wifi reload
          EOF
          chmod +x files/etc/uci-defaults/99-custom-settings

      - name: Download custom config
        run: |
          cd openwrt
          # Altere o link abaixo para o config correto do seu target
          wget -O .config "https://raw.githubusercontent.com/realroboto/openwrt/refs/heads/main/.config"
          make defconfig
          echo "Configuração final:"
          grep CONFIG_TARGET .config | head

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: dl-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: |
            dl-

      - name: Build OpenWrt firmware
        env:
          TAILSCALE_KEY: ${{ secrets.TAILSCALE_KEY }}
        run: |
          cd openwrt
          echo "🔧 Iniciando compilação..."
          make -j$(nproc) V=s || (echo "❌ Build falhou!" && exit 1)
          echo "✅ Build concluído."

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/
