name: Build OpenWrt (Ubuntu 24.04)

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev libelf-dev \
            python3 python3-pip python3-setuptools \
            rsync unzip zlib1g-dev file wget curl cpio time patch quilt \
            libtool autopoint autoconf automake pkg-config libglib2.0-dev \
            libxml-parser-perl intltool gettext-base \
            libgmp-dev libmpc-dev libmpfr-dev libreadline-dev \
            liblz4-dev libzstd-dev liblzma-dev libbz2-dev libzip-dev \
            libpcap-dev libnl-3-dev libnl-genl-3-dev libpam0g-dev libgnutls28-dev \
            libsodium-dev libgcrypt20-dev nettle-dev \
            zip p7zip-full xz-utils zstd lzip tar swig gperf \
            device-tree-compiler xmlstarlet xsltproc docbook-xsl docbook-xml \
            perl ecj fastjar openjdk-11-jdk-headless java-common \
            asciidoc help2man subversion mercurial graphviz ccache

      - name: Cache OpenWRT downloads and build
        uses: actions/cache@v4
        with:
          path: |
            openwrt/dl
            openwrt/build_dir
            openwrt/staging_dir
          key: openwrt-${{ runner.os }}-${{ hashFiles('openwrt/feeds.conf.default', 'openwrt/.config') }}
          restore-keys: |
            openwrt-${{ runner.os }}-

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/pesa1234/openwrt.git
          cd openwrt
          git checkout next-r4.6.14.rss.mtk
          rm -rf ./feeds ./package/feeds
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add custom UCI configuration
        env:
          WIFIPASS: ${{ secrets.WIFIPASS }}
          TAILSCALE: ${{ secrets.TAILSCALE }}
          PPPOENAME: ${{ secrets.PPPOENAME }}
          PPPOEPASS: ${{ secrets.PPPOEPASS }}
        run: |
          cd openwrt
          mkdir -p files/etc/uci-defaults
          cat << 'EOF' > files/etc/uci-defaults/99-custom-settings
          #!/bin/sh
          # (mantém o mesmo conteúdo do seu script)
          EOF
          chmod +x files/etc/uci-defaults/99-custom-settings

      - name: Download custom config
        run: |
          cd openwrt
          wget -O .config "https://raw.githubusercontent.com/realroboto/openwrt/refs/heads/main/.config"
          make defconfig
          echo "Configuração final:"
          grep CONFIG_TARGET .config | head

      - name: Build OpenWrt firmware
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          echo "🔧 Iniciando compilação..."
          make download -j$(nproc)
          make -j$(nproc) || (df -h && du -sh build_dir staging_dir)
          echo "✅ Build concluído."

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/
